/**
 * RED-419 C3 / STEP-004: `cambium compile --write` (workspace) emits
 * `src/contracts.generated.ts` from every block-form `returns do … end`
 * gen, behind the RED-222 sentinel-overwrite guard (DEC-006/7/9).
 *
 * Drives the real CLI against a tmp-dir [package] workspace, then loads
 * the emitted TypeBox into AJV and round-trips it against the inline IR
 * schema. Requires `ruby` + `node` (the in-tree test contract).
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import Ajv from 'ajv';

const REPO_ROOT = process.cwd();
const CLI = join(REPO_ROOT, 'cli/cambium.mjs');

let ws: string;
beforeEach(() => {
  ws = mkdtempSync(join(tmpdir(), 'cambium-red419-c3-'));
});
afterEach(() => {
  if (ws && existsSync(ws)) rmSync(ws, { recursive: true, force: true });
});

function runCli(args: string[], cwd = ws) {
  return spawnSync('node', [CLI, ...args], { cwd, encoding: 'utf8', maxBuffer: 50 * 1024 * 1024 });
}

// Two block-form gens. AlphaGen carries every vocabulary feature;
// BetaGen is a minimal block — together they exercise ordering + recursion.
const ALPHA_GEN = `
class AlphaGen < GenModel
  model "omlx:stub"
  system "inline"

  returns do
    field :name, String
    field :count, Integer, optional: true
    field :tags, [String]
    field :status, String, enum: %w[active archived]
    field :note, String, description: "free text"
    field :details do
      field :summary, String
    end
    field :items, [] do
      field :label, String
    end
  end

  def analyze(input)
    generate "go" do
      with context: input
    end
  end
end
`;

const BETA_GEN = `
class BetaGen < GenModel
  model "omlx:stub"
  system "inline"

  returns do
    field :ok, Boolean
  end

  def analyze(input)
    generate "go"
  end
end
`;

function appWorkspace(gens: Record<string, string>): void {
  writeFileSync(
    join(ws, 'Genfile.toml'),
    `[package]\nname = "wstest"\nversion = "0.0.0"\n`,
  );
  mkdirSync(join(ws, 'app', 'gens'), { recursive: true });
  for (const [name, body] of Object.entries(gens)) {
    writeFileSync(join(ws, 'app', 'gens', name), body);
  }
}

const GENERATED = () => join(ws, 'src', 'contracts.generated.ts');

describe('RED-419 contracts.generated.ts (STEP-004)', () => {
  it('--write emits the file with sentinel, both exports, stable order, valid TypeBox', () => {
    appWorkspace({ 'beta.cmb.rb': BETA_GEN, 'alpha.cmb.rb': ALPHA_GEN });
    const r = runCli(['compile', '--write']);
    expect(r.status, (r.stderr ?? '') + (r.stdout ?? '')).toBe(0);

    expect(existsSync(GENERATED())).toBe(true);
    const content = readFileSync(GENERATED(), 'utf8');

    // Sentinel is the first line (DEC-007).
    expect(content.split('\n', 1)[0]).toBe(
      '// @generated by cambium — DO NOT EDIT. Regenerate with `cambium compile --write`.',
    );
    // Both exports + their inferred types.
    expect(content).toMatch(/export const AlphaGenOutput = Type\.Object\(/);
    expect(content).toMatch(/export type AlphaGenOutput = Static<typeof AlphaGenOutput>/);
    expect(content).toMatch(/export const BetaGenOutput = Type\.Object\(/);
    expect(content).toMatch(/export type BetaGenOutput = Static<typeof BetaGenOutput>/);
    // Deterministic ordering: sorted by class name → Alpha before Beta
    // (DEC-003), regardless of filesystem enumeration order.
    expect(content.indexOf('AlphaGenOutput')).toBeLessThan(content.indexOf('BetaGenOutput'));
    // The optional field is Type.Optional; the enum is a Union of Literals.
    expect(content).toMatch(/count: Type\.Optional\(Type\.Integer\(\)\)/);
    expect(content).toMatch(/Type\.Union\(\[Type\.Literal\("active"\), Type\.Literal\("archived"\)\]\)/);
  });

  it('re-running --write overwrites cleanly (sentinel present)', () => {
    appWorkspace({ 'alpha.cmb.rb': ALPHA_GEN });
    expect(runCli(['compile', '--write']).status).toBe(0);
    const first = readFileSync(GENERATED(), 'utf8');
    const r2 = runCli(['compile', '--write']);
    expect(r2.status, (r2.stderr ?? '') + (r2.stdout ?? '')).toBe(0);
    expect(readFileSync(GENERATED(), 'utf8')).toBe(first); // byte-stable
  });

  it('HARD-ERRORS when the target exists without the sentinel (DEC-009)', () => {
    appWorkspace({ 'alpha.cmb.rb': ALPHA_GEN });
    mkdirSync(join(ws, 'src'), { recursive: true });
    writeFileSync(GENERATED(), 'export const HandWritten = 1\n');
    const r = runCli(['compile', '--write']);
    expect(r.status).toBe(1);
    const out = (r.stderr ?? '') + (r.stdout ?? '');
    expect(out).toMatch(/refusing to overwrite/);
    expect(out).toMatch(/contracts\.generated\.ts/);
    // The hand-authored file is untouched.
    expect(readFileSync(GENERATED(), 'utf8')).toBe('export const HandWritten = 1\n');
  });

  it('a dry compile (no --write) writes nothing', () => {
    appWorkspace({ 'alpha.cmb.rb': ALPHA_GEN });
    const r = runCli(['compile']);
    expect(r.status).toBe(0);
    expect(existsSync(GENERATED())).toBe(false);
  });

  it('--out-dir does NOT write the contracts file into the workspace', () => {
    appWorkspace({ 'alpha.cmb.rb': ALPHA_GEN });
    const r = runCli(['compile', '--out-dir', join(ws, 'dist')]);
    expect(r.status).toBe(0);
    expect(existsSync(GENERATED())).toBe(false);
  });

  it('writes nothing when no gen uses a returns-do block (symbol-only workspace)', () => {
    const SYMBOL_GEN = `
class SymGen < GenModel
  model "omlx:stub"
  system "inline"
  returns AnalysisReport
  def analyze(input)
    generate "go"
  end
end
`;
    // No contracts.ts → name check is best-effort skipped (RED-373).
    appWorkspace({ 'sym.cmb.rb': SYMBOL_GEN });
    const r = runCli(['compile', '--write']);
    expect(r.status, (r.stderr ?? '') + (r.stdout ?? '')).toBe(0);
    expect(existsSync(GENERATED())).toBe(false);
  });

  it('the emitted TypeBox validates the same data as the inline IR schema (round-trip)', async () => {
    appWorkspace({ 'alpha.cmb.rb': ALPHA_GEN });
    expect(runCli(['compile', '--write']).status).toBe(0);

    // Inline IR schema as the compiler emits it.
    const irOut = spawnSync('ruby', [
      join(REPO_ROOT, 'ruby/cambium/compile.rb'),
      join(ws, 'app', 'gens', 'alpha.cmb.rb'),
      '--method', 'analyze',
    ], { encoding: 'utf8', maxBuffer: 5e7 });
    expect(irOut.status, irOut.stderr).toBe(0);
    const inline = JSON.parse(irOut.stdout).returnSchema;

    // Reconstruct the AlphaGenOutput TypeBox value from the generated
    // source (without a TS transpile step): extract the `Type.Object(...)`
    // expression and evaluate it against the real TypeBox `Type`. The
    // resulting JSON Schema is what a consumer importing the file would get.
    const genSrc = readFileSync(GENERATED(), 'utf8');
    const { Type } = await import('@sinclair/typebox');
    // Extract the `Type.Object(...)` expression for AlphaGenOutput.
    const m = genSrc.match(/export const AlphaGenOutput = (Type\.Object\([\s\S]*?\}, \{ additionalProperties: false, \$id: "AlphaGenOutput" \}\))/);
    expect(m, 'AlphaGenOutput expression not found in generated source').toBeTruthy();
    // eslint-disable-next-line no-new-func
    const typebox = new Function('Type', `return ${m![1]}`)(Type);

    const ajvI = new Ajv({ allErrors: true, strict: false });
    ajvI.addSchema(inline, inline.$id);
    const ajvT = new Ajv({ allErrors: true, strict: false });
    ajvT.addSchema(typebox, typebox.$id);
    const vi = ajvI.getSchema(inline.$id)!;
    const vt = ajvT.getSchema(typebox.$id)!;

    const samples = [
      { name: 'n', tags: ['x'], status: 'active', note: 'hi', details: { summary: 's' }, items: [{ label: 'L' }] }, // valid
      { name: 'n', tags: ['x'], status: 'active', note: 'hi', details: { summary: 's' }, items: [{ label: 'L' }], count: 3 }, // optional present
      { name: 'n', tags: ['x'], status: 'bogus', note: 'hi', details: { summary: 's' }, items: [{ label: 'L' }] }, // bad enum
      { tags: ['x'], status: 'active', note: 'hi', details: { summary: 's' }, items: [{ label: 'L' }] }, // missing required
      { name: 'n', tags: ['x'], status: 'active', note: 'hi', details: { summary: 's' }, items: [{ label: 'L' }], extra: 1 }, // addl prop
    ];
    for (const s of samples) {
      expect(vt(s)).toBe(vi(s));
    }
  });

  // ── DEC-010: class-name uniqueness + identifier safety (AUD-003 / SEC-LOW-1) ──

  it('HARD-ERRORS when two block-form gens share the same class name (DEC-010)', () => {
    // Two different files, same class name → collision → hard error before write.
    const DUPE_A = `
class DupeGen < GenModel
  model "omlx:stub"
  system "inline"
  returns do
    field :x, String
  end
  def analyze(input)
    generate "go"
  end
end
`;
    const DUPE_B = `
class DupeGen < GenModel
  model "omlx:stub"
  system "inline"
  returns do
    field :y, Integer
  end
  def analyze(input)
    generate "go"
  end
end
`;
    appWorkspace({ 'dupe_a.cmb.rb': DUPE_A.trimStart(), 'dupe_b.cmb.rb': DUPE_B.trimStart() });
    const r = runCli(['compile', '--write']);
    expect(r.status).toBe(1);
    const out = (r.stderr ?? '') + (r.stdout ?? '');
    expect(out).toMatch(/class-name collision/);
    expect(out).toMatch(/DupeGen/);
    // Both file names must appear in the error.
    expect(out).toMatch(/dupe_a\.cmb\.rb/);
    expect(out).toMatch(/dupe_b\.cmb\.rb/);
    // No file written.
    expect(existsSync(GENERATED())).toBe(false);
  });

  // ── DEC-010 part 2: empty-set file lifecycle (AUD-002) ───────────────────

  it('deletes a stale sentinel-marked contracts.generated.ts when the last block-form gen is removed (DEC-010)', () => {
    // Phase 1: write a block-form gen → file is generated.
    appWorkspace({ 'alpha.cmb.rb': ALPHA_GEN });
    expect(runCli(['compile', '--write']).status).toBe(0);
    expect(existsSync(GENERATED())).toBe(true);

    // Phase 2: remove the block-form gen, add a symbol-form gen instead.
    const SYMBOL_GEN = `
class SymGen < GenModel
  model "omlx:stub"
  system "inline"
  returns AnalysisReport
  def analyze(input)
    generate "go"
  end
end
`;
    // Overwrite workspace: only a symbol-form gen remains.
    writeFileSync(join(ws, 'app', 'gens', 'alpha.cmb.rb'), SYMBOL_GEN.trimStart());
    const r = runCli(['compile', '--write']);
    expect(r.status, (r.stderr ?? '') + (r.stdout ?? '')).toBe(0);
    // The stale generated file must have been deleted (DEC-010 empty-set lifecycle).
    expect(existsSync(GENERATED())).toBe(false);
    const out = (r.stderr ?? '') + (r.stdout ?? '');
    expect(out).toMatch(/removed.*contracts\.generated\.ts/);
  });

  it('HARD-ERRORS on empty-set when a non-sentinel file is in the contracts.generated.ts path (DEC-007/009)', () => {
    // A hand-authored file is in the way — must not be touched.
    const SYMBOL_GEN = `
class SymGen < GenModel
  model "omlx:stub"
  system "inline"
  returns AnalysisReport
  def analyze(input)
    generate "go"
  end
end
`;
    appWorkspace({ 'sym.cmb.rb': SYMBOL_GEN.trimStart() });
    mkdirSync(join(ws, 'src'), { recursive: true });
    writeFileSync(GENERATED(), 'export const HandWritten = 1\n');
    const r = runCli(['compile', '--write']);
    expect(r.status).toBe(1);
    const out = (r.stderr ?? '') + (r.stdout ?? '');
    expect(out).toMatch(/refusing to remove/);
    // The hand-authored file is untouched.
    expect(readFileSync(GENERATED(), 'utf8')).toBe('export const HandWritten = 1\n');
  });

  it('HARD-ERRORS when a gen class name is not a valid TS identifier (SEC-LOW-1)', async () => {
    // A namespaced Ruby class name (Foo::Bar) yields "Foo::Bar" as entry.class,
    // which is not a valid bare TS identifier. The emitter must reject it before
    // writing a broken generated file.
    //
    // We drive the emitter directly (not via the full CLI) since Ruby itself
    // enforces that class names are constant paths — the emitter is the
    // right place to catch the remaining gap (DEV-004 in the change record).
    const { emitContractsFile } = await import(join(REPO_ROOT, 'cli/contracts-emitter.mjs'));
    const badClassSchema = {
      type: 'object',
      properties: { x: { type: 'string' } },
      required: ['x'],
      additionalProperties: false,
      $id: 'Foo::BarOutput',
    };
    expect(() => emitContractsFile({ 'Foo::Bar': badClassSchema })).toThrow(
      /not a valid TypeScript identifier/,
    );
  });

  // ── SEC-LOW-2: emitter escaping regression ────────────────────────────────
  //
  // Adversarial field names, enum values, and description strings containing
  // injection payloads must be escaped by the emitter so the generated TS is
  // a single inert quoted literal — the injected code does not execute.

  it('emitter escapes adversarial field names, enum values, and description strings (SEC-LOW-2)', async () => {
    const { emitContractsFile } = await import(join(REPO_ROOT, 'cli/contracts-emitter.mjs'));

    // Schema with adversarial strings in every injection-relevant position.
    const INJECTION_PAYLOAD = '${process.exit(1)}';
    const adversarialSchema = {
      type: 'object',
      properties: {
        // A field whose name needs quoting (not a bare identifier).
        'field"with"quotes': { type: 'string' },
        // A field with a description containing all the injection candidates.
        safe: {
          type: 'string',
          description: `contains " and \\ and \` and ${INJECTION_PAYLOAD} and \n a newline`,
        },
        // An enum field whose values contain injection payloads.
        status: {
          type: 'string',
          enum: [
            'ok',
            `val"with"quotes`,
            `val\\with\\backslash`,
            INJECTION_PAYLOAD,
          ],
        },
      },
      required: ['safe', 'status'],
      additionalProperties: false,
      $id: 'AdversarialOutput',
    };

    const src = emitContractsFile({ Adversarial: adversarialSchema });

    // 1. The injection payload must only appear inside double-quoted string
    //    literals, never as a bare expression. JSON.stringify wraps all values
    //    in double-quote strings, which means `${...}` is inert TS (template
    //    interpolation only fires inside backtick strings). Verify: every
    //    occurrence is surrounded by `"…"` — i.e., all matches are inside a
    //    JSON.stringify-escaped string literal and NOT inside a backtick string.
    //    The generated output uses double-quote string literals exclusively
    //    (emitter style), so `${process.exit(1)}` is a string value, not code.
    expect(src).not.toMatch(/`[^`]*process\.exit[^`]*`/); // not in a template literal

    // 3. Every adversarial string must appear in the output (it wasn't dropped)
    //    but only inside a string literal (JSON.stringify-escaped).
    expect(src).toContain('"field\\"with\\"quotes"'); // quoted key
    expect(src).toContain('val\\"with\\"quotes');       // escaped in enum literal
    expect(src).toContain('val\\\\with\\\\backslash');  // escaped backslash

    // 4. The output is a single valid source string (no syntax error caused by
    //    the newline in description). Newlines in JSON.stringify become \\n.
    expect(src).toMatch(/description:.*\\n.*a newline/);

    // 5. Backtick injection in description: JSON.stringify wraps in double-
    //    quotes, so a raw backtick in the description is safe (it's inside "…").
    expect(src).toContain('`');  // the backtick IS present...
    // ...but it cannot close a template literal because it's inside a double-quoted string.
    // Verify: description value is `{ description: "...`..." }` not `{ description: `...` }`.
    expect(src).toMatch(/description: "/);
  });
});
