// ── RED-419 C3: JSON Schema → TypeBox source emitter ──────────────────
//
// Hand-rolled (no `json-schema-to-typebox` dep — supply-chain policy)
// emitter over the CLOSED vocabulary that `returns do … end` produces
// (DEC-005/DEC-008): String/Integer/Float/Boolean scalars, `[T]` arrays,
// nested objects, array-of-object, `enum:` on String only, `optional:`
// (→ omitted from `required`), and an optional per-field `description:`.
//
// Input is the inline `returnSchema` object the Ruby compiler emits into
// the IR — already Draft-07, already `additionalProperties: false` at
// every object level, top-level `$id: "<ClassName>Output"`. The emitter
// is a pure function `(schema) → TypeBox source`, recursive, mirroring
// the conventions in `src/contracts.ts` (Type.Object(..., { additional-
// Properties: false, $id }), Type.Array, Type.Optional, Type.Union of
// Type.Literal for enums, `{ description }` annotations).
//
// This file writes NOTHING — it builds strings. The guarded write lives
// in compile.mjs (sentinel + escape check, RED-222 family).

// The exact first line every generated file carries (DEC-007, one-way
// door — ratified). Tools and the overwrite guard key on the substring
// `@generated by cambium`.
export const SENTINEL_LINE =
  '// @generated by cambium — DO NOT EDIT. Regenerate with `cambium compile --write`.';

/** The substring the overwrite guard checks for on a file's first line. */
export const SENTINEL_MARKER = '@generated by cambium';

const SCALAR_TYPEBOX = {
  string: 'Type.String',
  integer: 'Type.Integer',
  number: 'Type.Number',
  boolean: 'Type.Boolean',
};

/** Emit a TS string literal for a description annotation. */
function jsString(s) {
  return JSON.stringify(String(s));
}

/**
 * Recursively emit the TypeBox source for one JSON Schema fragment from
 * the closed vocabulary. `indent` is the current indentation string used
 * to pretty-print nested objects.
 */
function emitNode(schema, indent) {
  // Array → Type.Array(<items>)
  if (schema.type === 'array') {
    return `Type.Array(${emitNode(schema.items, indent)})`;
  }

  // Object → Type.Object({ ... }, { additionalProperties: false[, $id] })
  if (schema.type === 'object') {
    return emitObject(schema, indent);
  }

  // String with enum → Type.Union([Type.Literal('a'), ...])
  if (schema.type === 'string' && Array.isArray(schema.enum)) {
    const members = schema.enum.map((v) => `Type.Literal(${jsString(v)})`).join(', ');
    return withOptions(`Type.Union([${members}])`, schema);
  }

  // Scalar
  const ctor = SCALAR_TYPEBOX[schema.type];
  if (!ctor) {
    // Defensive: the closed vocabulary should never produce an unknown
    // node. If it does, fail loudly rather than emit broken TS.
    throw new Error(
      `contracts-emitter: unsupported JSON Schema node (type=${JSON.stringify(schema.type)}). ` +
        `The returns-block vocabulary is closed; this indicates a compiler/emitter drift.`,
    );
  }
  return withOptions(`${ctor}()`, schema, /* hasCall */ true);
}

/**
 * Attach a `{ description }` options object to a TypeBox constructor call
 * when the schema carries a description. For zero-arg ctors like
 * `Type.String()` we inject the options as the first argument; for the
 * enum's `Type.Union([...])` we append a second argument.
 */
function withOptions(expr, schema, hasCall = false) {
  if (schema.description === undefined) return expr;
  const opts = `{ description: ${jsString(schema.description)} }`;
  if (hasCall && expr.endsWith('()')) {
    // Type.String() → Type.String({ description: ... })
    return `${expr.slice(0, -1)}${opts})`;
  }
  // Type.Union([...]) → Type.Union([...], { description: ... })
  return `${expr.slice(0, -1)}, ${opts})`;
}

function emitObject(schema, indent) {
  const inner = indent + '  ';
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const lines = [];
  for (const [name, child] of Object.entries(props)) {
    let value = emitNode(child, inner);
    if (!required.has(name)) value = `Type.Optional(${value})`;
    lines.push(`${inner}${tsKey(name)}: ${value},`);
  }

  const optionParts = ['additionalProperties: false'];
  if (schema.$id !== undefined) optionParts.push(`$id: ${jsString(schema.$id)}`);
  const optionsObj = `{ ${optionParts.join(', ')} }`;

  if (lines.length === 0) {
    return `Type.Object({}, ${optionsObj})`;
  }
  return `Type.Object({\n${lines.join('\n')}\n${indent}}, ${optionsObj})`;
}

/** Quote a property key only when it isn't a safe bare identifier. */
function tsKey(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : jsString(name);
}

/**
 * Build the full `contracts.generated.ts` content from a map of
 * `{ ClassName: returnSchema }`. Deterministic: gens are sorted by class
 * name for stable diffs (DEC-003). Each block-form gen yields:
 *   export const <ClassName>Output = <typebox>
 *   export type <ClassName>Output = Static<typeof <ClassName>Output>
 *
 * @param {Record<string, any>} schemasByClass  className → inline returnSchema
 * @returns {string} full file content (ends with a trailing newline)
 */
/** Regex that a string must match to be safe as a bare TS identifier. */
const TS_IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function emitContractsFile(schemasByClass) {
  const classNames = Object.keys(schemasByClass).sort();
  const blocks = [];
  for (const className of classNames) {
    // SEC-LOW-1 / DEC-010: validate the class name before interpolating it
    // into the generated source as a bare TS identifier. Ruby constant-path
    // names (Foo::Bar) are the realistic failure mode; they produce broken
    // TS if emitted raw. Hard-error here rather than emitting broken output.
    if (!TS_IDENTIFIER_RE.test(className)) {
      throw new Error(
        `cambium compile: gen class name "${className}" is not a valid TypeScript ` +
          `identifier and cannot be emitted into contracts.generated.ts. ` +
          `Rename the class to a simple identifier (e.g. rename "Foo::Bar" to "FooBar"), ` +
          `or use \`returns :Symbol\` to reference a hand-written TypeBox contract.`,
      );
    }
    const exportName = `${className}Output`;
    const typebox = emitObject(schemasByClass[className], '');
    blocks.push(
      `export const ${exportName} = ${typebox}\n\n` +
        `export type ${exportName} = Static<typeof ${exportName}>`,
    );
  }

  const header = [
    SENTINEL_LINE,
    '//',
    '// TypeBox contracts generated from `returns do … end` blocks (RED-419).',
    '// Schema validation at runtime uses the inline IR schema, not this file;',
    '// this exists for typed consumer imports only.',
    "import { Type, type Static } from '@sinclair/typebox'",
  ].join('\n');

  return `${header}\n\n${blocks.join('\n\n')}\n`;
}
